### ISSUE TITLE
Followed quickstart, but no kernels, did I miss something?

### ISSUE THREAD

**Issue by rathboma** [tkestack/elastic-jupyter-operator#56]
Hey folks,

Firstly - thank you so much for starting this project! It looks really promising, very excited to try it out.

Disclaimer: I'm not super familiar with enterprise gateway, so I might just be doing something stupid (likely).

I ran `make deploy`, then followed the quickstart guide. Everything worked, but when I went to `localhost:8888` I get an empty notebook with no kernels....

Was I supposed to do something else? I feel like I'm just missing a step.

Thanks for pointing me in the right direction!

![image](https://user-images.githubusercontent.com/279769/151460695-a544a83a-9f5a-424c-943a-236f5d98c94a.png)

Matthew

**Comment by gaocegege** [comment]
Hi, are you familiar with Kubernetes? Can you please show the log of the operator? 

And could you please run the command `kubectl get pods`?

**Comment by rathboma** [comment]
Hey! I have both the gateway and the notebook pods running:

![image](https://user-images.githubusercontent.com/279769/152011279-9244e6ba-9e88-4500-867e-b4c5998b9f7d.png)

**Comment by rathboma** [comment]
Never mind, I realized I need to apply a kernel spec too. I'll make a documentation PR if I can later this week
